"""narrative, kits, claims

Revision ID: 36880733706e
Revises: 
Create Date: 2026-09-19 23:20:49.010770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36880733706e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('sensitive_market', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_slug'), 'kit', ['slug'], unique=True)
    op.create_table('narrative',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('sensitive_reviewer', sa.Text(), nullable=False),
    sa.Column('never_say', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_request',
    sa.Column('kit_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('need', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kit_id', 'id')
    )
    op.create_table('pillar',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('narrative_id', sa.SmallInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narrative.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_point',
    sa.Column('kit_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kit_id', 'id')
    )
    op.create_table('claim',
    sa.Column('kit_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pillar_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_kind', sa.String(length=16), nullable=True),
    sa.Column('evidence_proof_point_id', sa.String(length=64), nullable=True),
    sa.Column('flag_state', sa.String(length=16), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(evidence_kind = 'proof_point' AND evidence_proof_point_id IS NOT NULL) OR (evidence_kind = 'pillar' AND pillar_id IS NOT NULL) OR (evidence_kind IS NULL AND evidence_proof_point_id IS NULL)", name='claim_evidence_consistent'),
    sa.CheckConstraint("(flag_state = 'flagged') = (flag_reason IS NOT NULL)", name='claim_flag_has_reason'),
    sa.ForeignKeyConstraint(['kit_id', 'evidence_proof_point_id'], ['proof_point.kit_id', 'proof_point.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kit_id'], ['kit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillar.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('kit_id', 'id')
    )
    op.create_index(op.f('ix_claim_asset_type'), 'claim', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_asset_type'), table_name='claim')
    op.drop_table('claim')
    op.drop_table('proof_point')
    op.drop_table('pillar')
    op.drop_table('evidence_request')
    op.drop_table('narrative')
    op.drop_index(op.f('ix_kit_slug'), table_name='kit')
    op.drop_table('kit')
    # ### end Alembic commands ###
