"""claude call log

Revision ID: 4c7ee4978b9a
Revises: 36880733706e
Create Date: 2026-09-22 08:24:12.048040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7ee4978b9a'
down_revision: Union[str, Sequence[str], None] = '36880733706e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claude_call',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kit_id', sa.String(length=64), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claude_call_created_at'), 'claude_call', ['created_at'], unique=False)
    op.create_index(op.f('ix_claude_call_kit_id'), 'claude_call', ['kit_id'], unique=False)
    op.create_index(op.f('ix_claude_call_run_id'), 'claude_call', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claude_call_run_id'), table_name='claude_call')
    op.drop_index(op.f('ix_claude_call_kit_id'), table_name='claude_call')
    op.drop_index(op.f('ix_claude_call_created_at'), table_name='claude_call')
    op.drop_table('claude_call')
    # ### end Alembic commands ###
